## Note, "[ci skio]" or "[skip ci]" within a commit message _should_
##  cause Travis Continuous Integration to skip the following


## Clone settings for repository
##   1. reduce log _fluff_ with `true`
##   2. clone submodules when cloning this branch with `true`
##   3. clone the whole Git history with `false`, or set integer limit
git:
  quite: true
  submodules: true
  depth: false


## The dialect that will be spoken
language: bash


## Things to keep between CI runs
# cache:
#   directories:


## Operating systems to spin-up
##   1. when `true` some blocks such as `script` terminates at first failure
##   2. list of OS configurations (FrontMater _blocks_) Travis should test with
matrix:
  fast_finish: true
  include:
    ## Default 'dist' was 'trusty' as of 2019
    - name: 'Linux Xenial'
      os: linux
      dist: xenial


## Retrict what branches are cloned with Git
##   1. fetch `only` `gh-pages` or _`test-`_ prefixed branches
##   2. specifically ignore fetching the `master` branch
branches:
  only:
    - example
    - /^(?i:test)-.*$/
  except:
    - master


## Install deps and run CI tests
##   Note, `true` passes any normally required steps
before_install: true
install: true
script:
  - bash example-usage.sh || echo 'Success testing failure!'
